name: Metrics (examples)
on:
  schedule:
    - cron: "0 8 * * 0" # every Sunday at 8am UTC
  workflow_dispatch:
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    if: "github.repository == 'Florin-Catalin/Florin-Catalin'"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRIC_TOKEN }}

      - name: Get current year
        id: year
        run: echo "value=$(date +'%Y')" >> $GITHUB_OUTPUT

      # ======================================================================================
      
      
        # 🌇 GitHub Skyline 3D calendar

      - name: 🌇 GitHub Skyline 3D calendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          token: NOT_NEEDED
          plugin_skyline: yes
          plugin_skyline_year: ${{ steps.year.outputs.value }}
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugins_errors_fatal: ${{ github.repository == 'Florin-Catalin/Florin-Catalin' }}
          output_action: commit
          committer_message: "Update {filename} - [Skip GitHub Action]"

      # ======================================================================================
       # 📅 Isometric commit calendar

      - name: 📅 Isocalendar plugin (half year)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRIC_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: ${{ github.repository == 'Florin-Catalin/Florin-Catalin' }}
          output_action: commit
          committer_message: "Update {filename} - [Skip GitHub Action]"

      - name: 📅 Isocalendar plugin (full year)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRIC_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: ${{ github.repository == 'Florin-Catalin/Florin-Catalin' }}
          output_action: commit
          committer_message: "Update {filename} - [Skip GitHub Action]"
          
          
      - name: 🈷️ Languages plugin (indepth analysis)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRIC_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugins_errors_fatal: ${{ github.repository == 'Florin-Catalin/Florin-Catalin' }}
          output_action: commit
          committer_message: "Update {filename} - [Skip GitHub Action]"
